### ISSUE TITLE
openfile not working properly (file formats error)

### ISSUE THREAD

**Issue by amirhoseinjfri** [kalucky0/UnityFileBrowser#1]
hi

when i try to openfile it open dilog but the extenstion are wrong . you can check even the example thanks

**Comment by kalucky0** [comment]
What OS and Unity version are you using?

**Comment by amirhoseinjfri** [comment]
Sorry for delay
Windows 11 64 bit

**Comment by kalucky0** [comment]
I don't have a Windows machine but I'll ask my friends if they can test it. Just making sure but you mean that when you open a file dialog the allowed extensions are incorrect, right?

**Comment by amirhoseinjfri** [comment]
yes the extention will go something like this when dilog open

*.j
insted
*.jpg

**Comment by BoCai666** [comment]
i meet the same bug in windows

**Comment by Mo-enen** [comment]
same bug here. 
![Screenshot](https://github.com/kalucky0/UnityFileBrowser/assets/13920065/818a4ca6-5171-4ceb-b020-e77e8768f1e2)

**Comment by kalucky0** [comment]
Should be fixed in [v0.2.2](https://github.com/kalucky0/UnityFileBrowser/releases)
